#!/bin/bash
# Deploy ezlocalai - Local AI Inference Server (macOS)
# Clones ezlocalai, creates a Python venv, installs it, configures env vars, and starts the server.
set -e

INSTALL_DIR="${EZLOCALAI_INSTALL_DIR:-$HOME/ezlocalai}"
DEFAULT_MODEL="${EZLOCALAI_DEFAULT_MODEL:-unsloth/Qwen3.5-4B-GGUF}"
LLM_MAX_TOKENS="${EZLOCALAI_MAX_TOKENS:-40000}"
EZLOCALAI_PORT="${EZLOCALAI_PORT:-8091}"
EZLOCALAI_API_KEY="${EZLOCALAI_API_KEY:-}"
WHISPER_MODEL="${EZLOCALAI_WHISPER_MODEL:-large-v3}"
IMG_MODEL="${EZLOCALAI_IMG_MODEL:-Tongyi-MAI/Z-Image-Turbo}"
TTS_ENABLED="${EZLOCALAI_TTS_ENABLED:-true}"
STT_ENABLED="${EZLOCALAI_STT_ENABLED:-true}"
QUANT_TYPE="${EZLOCALAI_QUANT_TYPE:-Q4_K_XL}"
LLM_BATCH_SIZE="${EZLOCALAI_BATCH_SIZE:-2048}"
VOICE_SERVER="${EZLOCALAI_VOICE_SERVER:-}"
IMAGE_SERVER="${EZLOCALAI_IMAGE_SERVER:-}"
TEXT_SERVER="${EZLOCALAI_TEXT_SERVER:-}"
PYTHON_VERSION="${PYTHON_VERSION:-3.11}"
REPO_URL="https://github.com/DevXT-LLC/ezlocalai.git"

# If IMG_MODEL doesn't contain a "/", treat it as disabled (empty)
if [[ "${IMG_MODEL}" != */* ]]; then
    IMG_MODEL=""
fi

echo "============================================="
echo "  ezlocalai Deployment Script (macOS)"
echo "============================================="
echo ""
echo "Install directory: ${INSTALL_DIR}"
echo "Default model:     ${DEFAULT_MODEL}"
echo "Max tokens:        ${LLM_MAX_TOKENS}"
echo "Port:              ${EZLOCALAI_PORT}"
echo ""

# ------------------------------------------------------------------
# 1. Ensure Python is available
# ------------------------------------------------------------------
PYTHON_CMD=""
for candidate in "python${PYTHON_VERSION}" "python3" "python"; do
    if command -v "$candidate" &>/dev/null; then
        PYTHON_CMD="$candidate"
        break
    fi
done

if [ -z "$PYTHON_CMD" ]; then
    echo "ERROR: Python not found. Please install Python ${PYTHON_VERSION}+ first."
    echo "You can install it via: brew install python@${PYTHON_VERSION}"
    exit 1
fi

PYTHON_VER=$("$PYTHON_CMD" --version 2>&1 | awk '{print $2}')
echo "Using Python: ${PYTHON_CMD} (${PYTHON_VER})"

# ------------------------------------------------------------------
# 2. Ensure git is available
# ------------------------------------------------------------------
if ! command -v git &>/dev/null; then
    echo "ERROR: git is not installed. Please install git first."
    echo "You can install it via: xcode-select --install"
    exit 1
fi

# ------------------------------------------------------------------
# 3. Clone or update the repository
# ------------------------------------------------------------------
if [ -d "${INSTALL_DIR}/.git" ]; then
    echo "Updating existing ezlocalai installation..."
    cd "${INSTALL_DIR}"
    git pull --ff-only || {
        echo "WARNING: git pull failed, continuing with existing code."
    }
else
    echo "Cloning ezlocalai repository..."
    mkdir -p "$(dirname "${INSTALL_DIR}")"
    git clone "${REPO_URL}" "${INSTALL_DIR}"
    cd "${INSTALL_DIR}"
fi

# ------------------------------------------------------------------
# 4. Create / update virtual environment
# ------------------------------------------------------------------
VENV_DIR="${INSTALL_DIR}/.venv"
if [ ! -d "${VENV_DIR}" ]; then
    echo "Creating virtual environment..."
    "$PYTHON_CMD" -m venv "${VENV_DIR}"
fi

# Activate venv
source "${VENV_DIR}/bin/activate"
echo "Virtual environment active: ${VENV_DIR}"

# Upgrade pip
pip install --upgrade pip -q

# ------------------------------------------------------------------
# 4b. Install uv for faster package management
# ------------------------------------------------------------------
UV_AVAILABLE=false
if pip install uv -q 2>/dev/null; then
    UV_AVAILABLE=true
    echo "Using uv for fast package installation."
else
    echo "uv not available, using pip (slower but functional)."
fi

# Helper: install packages via uv (preferred) or pip (fallback)
pkg_install() {
    if $UV_AVAILABLE; then
        uv pip install "$@"
    else
        pip install "$@"
    fi
}

# ------------------------------------------------------------------
# 5. Install ezlocalai in editable mode + dependencies
# ------------------------------------------------------------------
echo "Installing ezlocalai..."
cd "${INSTALL_DIR}"
pkg_install -e . -q

# Install runtime dependencies (requirements.txt has uvicorn, fastapi, etc.)
if [ -f "${INSTALL_DIR}/requirements.txt" ]; then
    echo "Installing runtime dependencies..."
    pkg_install -r "${INSTALL_DIR}/requirements.txt" -q 2>&1 | tail -5 || true
fi

# ------------------------------------------------------------------
# 6. Write environment configuration
# ------------------------------------------------------------------
ENV_FILE="${INSTALL_DIR}/.env"
echo "Writing environment configuration to ${ENV_FILE}..."

cat > "${ENV_FILE}" <<ENVEOF
# ezlocalai configuration - generated by deployment script
DEFAULT_MODEL=${DEFAULT_MODEL}
LLM_MAX_TOKENS=${LLM_MAX_TOKENS}
EZLOCALAI_URL=http://0.0.0.0:${EZLOCALAI_PORT}
EZLOCALAI_API_KEY=${EZLOCALAI_API_KEY}
WHISPER_MODEL=${WHISPER_MODEL}
IMG_MODEL=${IMG_MODEL}
TTS_ENABLED=${TTS_ENABLED}
STT_ENABLED=${STT_ENABLED}
QUANT_TYPE=${QUANT_TYPE}
LLM_BATCH_SIZE=${LLM_BATCH_SIZE}
VOICE_SERVER=${VOICE_SERVER}
IMAGE_SERVER=${IMAGE_SERVER}
TEXT_SERVER=${TEXT_SERVER}
ENVEOF

echo "Configuration written."

# ------------------------------------------------------------------
# 7. Create launchd plist for auto-start (macOS)
# ------------------------------------------------------------------
PLIST_DIR="$HOME/Library/LaunchAgents"
PLIST_FILE="${PLIST_DIR}/com.devxt.ezlocalai.plist"
mkdir -p "${PLIST_DIR}"

cat > "${PLIST_FILE}" <<PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.devxt.ezlocalai</string>
    <key>ProgramArguments</key>
    <array>
        <string>${VENV_DIR}/bin/ezlocalai</string>
        <string>start</string>
        <string>--model</string>
        <string>${DEFAULT_MODEL}</string>
    </array>
    <key>WorkingDirectory</key>
    <string>${INSTALL_DIR}</string>
    <key>RunAtLoad</key>
    <false/>
    <key>KeepAlive</key>
    <false/>
    <key>StandardOutPath</key>
    <string>${INSTALL_DIR}/logs/ezlocalai.log</string>
    <key>StandardErrorPath</key>
    <string>${INSTALL_DIR}/logs/ezlocalai-error.log</string>
</dict>
</plist>
PLISTEOF

mkdir -p "${INSTALL_DIR}/logs"
echo "LaunchAgent plist created at ${PLIST_FILE}"

# ------------------------------------------------------------------
# 8. Create management wrapper scripts
# ------------------------------------------------------------------
SCRIPTS_DIR="${INSTALL_DIR}/scripts"
mkdir -p "${SCRIPTS_DIR}"

cat > "${SCRIPTS_DIR}/start.sh" <<'STARTEOF'
#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "${SCRIPT_DIR}/.venv/bin/activate"
cd "${SCRIPT_DIR}"
ezlocalai start "$@"
STARTEOF
chmod +x "${SCRIPTS_DIR}/start.sh"

cat > "${SCRIPTS_DIR}/stop.sh" <<'STOPEOF'
#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "${SCRIPT_DIR}/.venv/bin/activate"
cd "${SCRIPT_DIR}"
ezlocalai stop
STOPEOF
chmod +x "${SCRIPTS_DIR}/stop.sh"

cat > "${SCRIPTS_DIR}/restart.sh" <<'RESTARTEOF'
#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "${SCRIPT_DIR}/.venv/bin/activate"
cd "${SCRIPT_DIR}"
ezlocalai restart "$@"
RESTARTEOF
chmod +x "${SCRIPTS_DIR}/restart.sh"

cat > "${SCRIPTS_DIR}/status.sh" <<'STATUSEOF'
#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "${SCRIPT_DIR}/.venv/bin/activate"
cd "${SCRIPT_DIR}"
ezlocalai status
STATUSEOF
chmod +x "${SCRIPTS_DIR}/status.sh"

cat > "${SCRIPTS_DIR}/logs.sh" <<'LOGSEOF'
#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "${SCRIPT_DIR}/.venv/bin/activate"
cd "${SCRIPT_DIR}"
ezlocalai logs -f
LOGSEOF
chmod +x "${SCRIPTS_DIR}/logs.sh"

echo ""
echo "============================================="
echo "  ezlocalai Deployment Complete!"
echo "============================================="
echo ""
echo "Installation directory: ${INSTALL_DIR}"
echo "Virtual environment:    ${VENV_DIR}"
echo "Configuration file:     ${ENV_FILE}"
echo ""
echo "Management commands (activate venv first):"
echo "  source ${VENV_DIR}/bin/activate"
echo "  ezlocalai start        # Start the server"
echo "  ezlocalai stop         # Stop the server"
echo "  ezlocalai restart      # Restart the server"
echo "  ezlocalai status       # Check server status"
echo "  ezlocalai logs -f      # Follow server logs"
echo ""
echo "Or use the wrapper scripts:"
echo "  ${SCRIPTS_DIR}/start.sh"
echo "  ${SCRIPTS_DIR}/stop.sh"
echo "  ${SCRIPTS_DIR}/restart.sh"
echo "  ${SCRIPTS_DIR}/status.sh"
echo "  ${SCRIPTS_DIR}/logs.sh"
echo ""
echo "macOS LaunchAgent (load/unload):"
echo "  launchctl load ${PLIST_FILE}"
echo "  launchctl unload ${PLIST_FILE}"
echo ""
LOCAL_IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "localhost")
echo "Server will be available at: http://${LOCAL_IP}:${EZLOCALAI_PORT}"

# ------------------------------------------------------------------
# 9. Start the server
# ------------------------------------------------------------------
echo ""
echo "Starting ezlocalai..."
source "${VENV_DIR}/bin/activate"
cd "${INSTALL_DIR}"
ezlocalai start --model "${DEFAULT_MODEL}"
