#!/bin/bash
# Deploy ezlocalai - Local AI Inference Server
# Clones ezlocalai, creates a Python venv with the CLI, then uses the CLI to manage Docker.
# The CLI auto-detects GPU type (NVIDIA, Jetson, AMD, CPU) and uses the correct Docker Compose file.
set -e

INSTALL_DIR="${EZLOCALAI_INSTALL_DIR:-/opt/ezlocalai}"
DEFAULT_MODEL="${EZLOCALAI_DEFAULT_MODEL:-unsloth/Qwen3.5-4B-GGUF}"
EZLOCALAI_PORT="${EZLOCALAI_PORT:-8091}"
EZLOCALAI_API_KEY="${EZLOCALAI_API_KEY:-}"
VOICE_SERVER="${EZLOCALAI_VOICE_SERVER:-}"
IMAGE_SERVER="${EZLOCALAI_IMAGE_SERVER:-}"
TEXT_SERVER="${EZLOCALAI_TEXT_SERVER:-}"
PYTHON_VERSION="${PYTHON_VERSION:-3.11}"
REPO_URL="https://github.com/DevXT-LLC/ezlocalai.git"

echo "============================================="
echo "  ezlocalai Deployment Script"
echo "============================================="
echo ""
echo "Install directory: ${INSTALL_DIR}"
echo "Default model:     ${DEFAULT_MODEL}"
echo "Port:              ${EZLOCALAI_PORT}"
echo ""

# ------------------------------------------------------------------
# 1. Ensure Python is available
# ------------------------------------------------------------------
PYTHON_CMD=""
for candidate in "python${PYTHON_VERSION}" "python3" "python"; do
    if command -v "$candidate" &>/dev/null; then
        PYTHON_CMD="$candidate"
        break
    fi
done

if [ -z "$PYTHON_CMD" ]; then
    echo "ERROR: Python not found. Please install Python ${PYTHON_VERSION}+ first."
    echo "You can use the 'install-python' deployment script."
    exit 1
fi

PYTHON_VER=$("$PYTHON_CMD" --version 2>&1 | awk '{print $2}')
echo "Using Python: ${PYTHON_CMD} (${PYTHON_VER})"

# Ensure python3-venv package is available on Debian/Ubuntu
if command -v apt-get &>/dev/null; then
    if ! "$PYTHON_CMD" -m venv --help &>/dev/null 2>&1; then
        echo "Installing python3-venv package..."
        sudo apt-get update -qq
        sudo apt-get install -y "python${PYTHON_VERSION}-venv" 2>/dev/null || \
            sudo apt-get install -y python3-venv 2>/dev/null || true
    fi
fi

# ------------------------------------------------------------------
# 2. Ensure git and Docker are available
# ------------------------------------------------------------------
if ! command -v git &>/dev/null; then
    echo "ERROR: git is not installed. Please install git first."
    echo "You can use the 'install-git' deployment script."
    exit 1
fi

if ! command -v docker &>/dev/null; then
    echo "ERROR: Docker is not installed. Please install Docker first."
    exit 1
fi

# ------------------------------------------------------------------
# 3. Clone or update the repository
# ------------------------------------------------------------------
if [ -d "${INSTALL_DIR}/.git" ]; then
    echo "Updating existing ezlocalai installation..."
    cd "${INSTALL_DIR}"
    git pull --ff-only || {
        echo "WARNING: git pull failed, continuing with existing code."
    }
else
    echo "Cloning ezlocalai repository..."
    sudo mkdir -p "$(dirname "${INSTALL_DIR}")"
    sudo mkdir -p "${INSTALL_DIR}"
    sudo chown -R "$(whoami):$(id -gn)" "${INSTALL_DIR}"
    git clone "${REPO_URL}" "${INSTALL_DIR}"
    cd "${INSTALL_DIR}"
fi

# Ensure the install directory is owned by the current user
if [ -d "${INSTALL_DIR}" ] && [ ! -w "${INSTALL_DIR}" ]; then
    echo "Fixing ownership of ${INSTALL_DIR}..."
    sudo chown -R "$(whoami):$(id -gn)" "${INSTALL_DIR}"
fi

# ------------------------------------------------------------------
# 4. Create venv and install CLI
# ------------------------------------------------------------------
VENV_DIR="${INSTALL_DIR}/.venv"
if [ ! -d "${VENV_DIR}" ]; then
    echo "Creating virtual environment..."
    "$PYTHON_CMD" -m venv "${VENV_DIR}"
fi

source "${VENV_DIR}/bin/activate"
echo "Virtual environment active: ${VENV_DIR}"

pip install --upgrade pip -q
echo "Installing ezlocalai CLI..."
cd "${INSTALL_DIR}"
pip install -e . -q

# ------------------------------------------------------------------
# 5. Ensure Docker starts on boot
# ------------------------------------------------------------------
echo "Ensuring Docker starts on boot..."
if command -v systemctl &>/dev/null; then
    sudo systemctl enable docker 2>/dev/null || true
    echo "✅ Docker enabled at boot"
else
    echo "⚠️  systemctl not found, skipping boot enable"
fi

# ------------------------------------------------------------------
# 6. Write environment configuration
# ------------------------------------------------------------------
ENV_FILE="${INSTALL_DIR}/.env"
echo "Writing environment configuration to ${ENV_FILE}..."

cat > "${ENV_FILE}" <<ENVEOF
# ezlocalai configuration - generated by deployment script
DEFAULT_MODEL=${DEFAULT_MODEL}
EZLOCALAI_URL=http://0.0.0.0:${EZLOCALAI_PORT}
EZLOCALAI_API_KEY=${EZLOCALAI_API_KEY}
VOICE_SERVER=${VOICE_SERVER}
IMAGE_SERVER=${IMAGE_SERVER}
TEXT_SERVER=${TEXT_SERVER}
ENVEOF

echo "Configuration written."

# ------------------------------------------------------------------
# 7. Start via CLI (handles GPU detection + Docker Compose)
# ------------------------------------------------------------------
echo ""
echo "Starting ezlocalai..."
ezlocalai start --model "${DEFAULT_MODEL}"

echo ""
echo "============================================="
echo "  ezlocalai Deployment Complete!"
echo "============================================="
echo ""
echo "Installation directory: ${INSTALL_DIR}"
echo "Virtual environment:    ${VENV_DIR}"
echo ""
echo "Management commands (activate venv first):"
echo "  source ${VENV_DIR}/bin/activate"
echo "  ezlocalai start        # Start the server"
echo "  ezlocalai stop         # Stop the server"
echo "  ezlocalai restart      # Restart the server"
echo "  ezlocalai status       # Check server status"
echo "  ezlocalai logs -f      # Follow server logs"
echo ""
LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || ip route get 1 2>/dev/null | awk '{print $7; exit}' || echo "localhost")
echo "Server will be available at: http://${LOCAL_IP}:${EZLOCALAI_PORT}"
